openapi: 3.0.0
info:
  title: Real Estate Listing API
  description: API for listing properties for sale or rent separately
  version: 1.0.0
servers:
  - url: http://127.0.0.1:8080/
paths:
  /sale/listings:
    get:
      summary: Get all sale listings
      operationId: getSaleListings
      responses:
        '200':
          description: A list of sale listings
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ListingsResponse'
        '404':
          description: No sale listings found
    post:
      summary: Create a new real estate listing for sale
      operationId: createSaleListing
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ListingRequest'
      responses:
        '201':
          description: Successfully created sale listing
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SaleListingResponse'
        '400':
          description: Bad request
  /rent/listings:
    get:
      summary: Get all rent listings
      operationId: getRentListings
      responses:
        '200':
          description: A list of rent listings
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ListingsResponse'
        '404':
          description: No rent listings found
    post:
      summary: Create a new real estate listing for rent
      operationId: createRentListing
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ListingRequest'
      responses:
        '201':
          description: Successfully created rent listing
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RentListingResponse'
        '400':
          description: Bad request
components:
  schemas:
    ListingRequest:
      type: object
      required:
        - city
        - street
        - house
        - flat
        - rooms
        - area
        - monthlyRent
        - price
        - description
      properties:
        city:
          type: string
          maxLength: 30
          example: "Saint Petersburg"
        street:
          type: string
          maxLength: 30
          example: "Kronverkskiy Prospekt"
        house:
          type: integer
          example: 49
        building:
          type: integer
          example: 1
        rooms:
          type: integer
          example: 44
          description: Number of rooms
        area:
          type: number
          format: float
          example: 1200.3
          description: Area of the property in square meters
        price:
          type: number
          format: float
          example: 10000
          description: Monthly rent price in RUB for rent and full price for sale
        description:
          type: string
          description: Detailed description of the property
          maxLength: 400
    SaleListingResponse:
      type: object
      properties:
        listingId:
          type: string
          description: Unique identifier for the newly created sale listing
        status:
          type: string
          description: Status of the sale listing creation
    RentListingResponse:
      type: object
      properties:
        listingId:
          type: string
          description: Unique identifier for the newly created rent listing
        status:
          type: string
          description: Status of the rent listing creation
    ListingsResponse:
      type: object
      properties:
        listingId:
          type: string
          description: Unique identifier for the listing
        type:
          type: string
          enum: [ apartment, house, commercial ]
          description: The type of property
        operation:
          type: string
          enum: [ sale, rent ]
          description: Type of operation (sale or rent)
        address:
          type: string
          description: Full address of the property
        area:
          type: number
          format: float
          description: Area of the property in square meters
        rooms:
          type: integer
          description: Number of rooms
        price:
          type: number
          format: float
          description: Price of the property in USD for sale or monthly rent for rent
        description:
          type: string
          description: Detailed description of the property
        photos:
          type: array
          items:
            type: string
            format: uri
          description: URLs to photos of the property