openapi: 3.0.3
info:
  title: Banking API Specification for account operations
  description: |-
    A simple banking API that allows two operations:
    - get account balance given account number
    - deposit amount to a account
  version: 1.0-SNAPSHOT
servers:
  - url: http://127.0.0.1:8080/
tags:
  - name: accounts
    description: Operations between bank accounts

paths:
  /account:
    get:
      tags:
        - accounts
      summary: Get account information
      description: Get account information using account number
      operationId: getAccount
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Profile'
        404:
          description: Account not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Profile'
  /account/deposit:
    post:
      tags:
        - accounts
      summary: Deposit amount to account
      description: Initiates a deposit operation of a desired amount to the account specified
      operationId: depositToAccount
      requestBody:
        description: Account number and desired amount to deposit
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateProfileRequest'
        required: true
      responses:
        204:
          description: Success
        404:
          description: Account not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountNotFoundError'
components:
  schemas:
    Profile:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        password:
          type: string
    AccountNotFoundError:
      type: object
      properties:
        message:
          type: string
    CreateProfileRequest:
      required:
        - name
        - password
        - mail
      type: object
      properties:
        name:
          type: string
        password:
          type: string
        mail:
          type: string