version: "3.9"

services:
  kafka:
    image: obsidiandynamics/kafka # support 2.3.0
    restart: "no"
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_BROKER_ID: 52
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_INTER_BROKER_LISTENER_NAME: DOCKER_INTERNAL
      KAFKA_LISTENERS: DOCKER_EXTERNAL://kafka:9092,OTHER_HOST://0.0.0.0:9093,DOCKER_INTERNAL://kafka:29092
      KAFKA_ADVERTISED_LISTENERS: DOCKER_EXTERNAL://localhost:9092,DOCKER_INTERNAL://kafka:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: DOCKER_EXTERNAL:PLAINTEXT,OTHER_HOST:PLAINTEXT,DOCKER_INTERNAL:PLAINTEXT
    depends_on:
      - zookeeper
    networks:
      - kafka-network
  
  zookeeper:
    image: zookeeper:3.7.2
    restart: "no"
    networks:
      - kafka-network
    ports:
      - "2181:2181"

networks:
  kafka-network:
    name: kafka-network
    driver: bridge
